# -*- coding: utf-8 -*-
"""Projeto_PDI.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1spz7lmxiARD1td0UGyptJkMXAXCRAiFX
"""

!pip install torch torchvision torchmetrics matplotlib segmentation-models-pytorch onnx onnx-tf tensorflow

import torch
import torchvision
import numpy as np
import matplotlib.pyplot as plt

from torch.utils.data import Dataset, DataLoader, Subset
from torchvision.datasets import OxfordIIITPet
from torchvision import transforms
from PIL import Image

DEVICE = "cuda" if torch.cuda.is_available() else "cpu"
IMG_SIZE = 128

class PetSegmentationDataset(Dataset):
    def __init__(self, root, split="trainval", img_size=128, download=True):
        self.dataset = OxfordIIITPet(
            root=root,
            split=split,
            target_types="segmentation",
            download=download
        )
        self.img_size = img_size

    def __len__(self):
        return len(self.dataset)

    def __getitem__(self, idx):
        image, mask = self.dataset[idx]

        image = image.resize((self.img_size, self.img_size))
        mask = mask.resize((self.img_size, self.img_size), resample=Image.NEAREST)

        image = transforms.ToTensor()(image)

        mask = np.array(mask)

        mask = (mask ==  1).astype(np.float32)

        mask = torch.tensor(mask).unsqueeze(0)

        return image, mask

train_dataset_full = PetSegmentationDataset(root="./data", split="trainval", img_size=IMG_SIZE)
test_dataset_full = PetSegmentationDataset(root="./data", split="test", img_size=IMG_SIZE)

train_dataset = Subset(train_dataset_full, range(1000))
test_dataset = Subset(test_dataset_full, range(200))

train_loader = DataLoader(train_dataset, batch_size=8, shuffle=True)
test_loader = DataLoader(test_dataset, batch_size=8, shuffle=False)

print("Treino:", len(train_dataset))
print("Teste:", len(test_dataset))

images, masks = next(iter(train_loader))

print("Imagem:", images.shape)
print("Máscara:", masks.shape)

plt.figure(figsize=(8,4))

plt.subplot(1,2,1)
plt.imshow(images[0].permute(1,2,0))
plt.title("Imagem")
plt.axis("off")

plt.subplot(1,2,2)
plt.imshow(masks[0][0], cmap="gray")
plt.title("Máscara")
plt.axis("off")

plt.show()

import segmentation_models_pytorch as smp

model = smp.Unet(
    encoder_name="resnet18",
    encoder_weights="imagenet",
    in_channels=3,
    classes=1
)

model = model.to(DEVICE)

print("Modelo carregado!")

import torch.nn as nn

criterion = nn.BCEWithLogitsLoss()

optimizer = torch.optim.Adam(
    model.parameters(),
    lr=1e-4
)

def train_epoch(model, loader, optimizer, criterion):
    model.train()

    running_loss = 0

    for images, masks in loader:

        images = images.to(DEVICE)
        masks = masks.to(DEVICE)

        optimizer.zero_grad()

        outputs = model(images)

        loss = criterion(outputs, masks)

        loss.backward()

        optimizer.step()

        running_loss += loss.item()

    return running_loss / len(loader)

EPOCHS = 10

for epoch in range(EPOCHS):
    loss = train_epoch(model, train_loader, optimizer, criterion)
    print(f"Epoch {epoch+1}/{EPOCHS} - Loss: {loss:.4f}")

model.eval()

image, mask = test_dataset[0]

with torch.no_grad():

    pred = model(
        image.unsqueeze(0).to(DEVICE)
    )

    pred = torch.sigmoid(pred)

    pred = pred.cpu().squeeze().numpy()
    plt.imshow(pred, cmap="gray")
    plt.colorbar()

from torchmetrics.classification import BinaryJaccardIndex
from torchmetrics.classification import BinaryAccuracy

iou_metric = BinaryJaccardIndex().to(DEVICE)
acc_metric = BinaryAccuracy().to(DEVICE)

model.eval()

iou_metric.reset()
acc_metric.reset()

with torch.no_grad():

    for images, masks in test_loader:

        images = images.to(DEVICE)
        masks = masks.to(DEVICE)

        outputs = model(images)

        outputs = torch.sigmoid(outputs)

        preds = (outputs > 0.5).float()

        iou_metric.update(preds, masks)
        acc_metric.update(preds, masks)

iou = iou_metric.compute().item()
acc = acc_metric.compute().item()

print(f"IoU: {iou:.4f}")
print(f"Acurácia: {acc:.4f}")

plt.figure(figsize=(12,4))

plt.subplot(1,3,1)
plt.imshow(image.permute(1,2,0))
plt.title("Imagem")
plt.axis("off")

plt.subplot(1,3,2)
plt.imshow(mask.squeeze(), cmap="gray")
plt.title("Ground Truth")
plt.axis("off")

plt.subplot(1,3,3)
plt.imshow(pred, cmap="gray")
plt.title("Predição")
plt.axis("off")

plt.savefig("resultado_segmentacao.png", dpi=200, bbox_inches="tight")
plt.show()

torch.save(model.state_dict(), "unet_pet_segmentation.pth")

!pip install onnx onnxscript

dummy_input = torch.randn(1, 3, IMG_SIZE, IMG_SIZE).to(DEVICE)

torch.onnx.export(
    model,
    dummy_input,
    "unet_pet_segmentation.onnx",
    input_names=["input"],
    output_names=["output"],
    opset_version=11
)

print("Modelo ONNX exportado!")

torch.save(model.state_dict(), "unet_pet_segmentation.pth")

with open("metricas.txt", "w") as f:
    f.write("IoU: 0.7903\n")
    f.write("Acurácia: 0.9304\n")

from google.colab import files

files.download("unet_pet_segmentation.pth")
files.download("unet_pet_segmentation.onnx")